title: CTB2210 - Constructiemechanica 3
author: Tom van Woudenberg, gemaakt met <a href="https://teachbooks.io">TeachBooks</a>, <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="license noopener noreferrer"">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt=""></a>
                                                     # Replace Author with your own name in the line above

execute:
  execute_notebooks: "off"                           # Replace this if you want don't have notebooks with output and you want to add notebook output during build

only_build_toc_files: true                           # Replace this with false if you want to build all files in the book, allowing you to refer to pages which are not included in the table of contents


html:
  baseurl :  "https://oit.tudelft.nl/CTB1310/2025"
  home_page_in_navbar       : true

sphinx:                                              # Options passed on to the underlying sphinx-parser
  config:
    language: nl                                     # Set language to Dutch
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js # Required for live code: https://teachbooks.io/manual/features/live_code.html
    thebe_config:
      use_thebe_lite: true                           # Required for live code: https://teachbooks.io/manual/features/live_code.html
      exclude_patterns: ["**/**"]
    html_theme_options:
      logo:
        text: CTB1310 - Constructiemechanica 2 2025/2026
      repository_url: "https://github.com/TUDelft-books/CTB1310/"
      path_to_docs: "book"                           # Required for edit_page_button, should be book if you're using TeachBooks package (https://github.com/TeachBooks/TeachBooks) or the TeachBooks deploy book workflow (https://teachbooks.io/manual/external/deploy-book-workflow/README.html)
      repository_branch: "2025"              # Replace when you change the name of your published branch (required for edit_page_button)
      use_repository_button: true                    # Replace with false if you don't want the repository button (i.e. if you have a private repo)
      use_edit_page_button: true
      use_issues_button : true                       # Replace with false if you don't want the issues button (i.e. if you don't want to use GitHub issues or have a private repo)
      launch_buttons:
        thebe: true                                  # Required for live code: https://teachbooks.io/manual/features/live_code.html
# START REMOVE-FROM-RELEASE
      announcement: "<p>This book is not the version shared with students. That one is available here <a href='https://oit.tudelft.nl/CTB1310' style='color: cyan;'>oit.tudelft.nl/CTB1310</a></p>"
    keep_warnings: true
# END REMOVE-FROM-RELEASE

    html_show_copyright: false                       # As the copyright is included in the author field
    html_last_updated_fmt: '%B %-d, %Y'              # Adds the date of the last update to the footer
    mathjax3_config:
      chtml: {
        mtextInheritFont: true                       # To typeset text within math prettier
      }
    named_colors_custom_colors: {'attributiongrey':[150,150,150]} # Custom colour for the attribution admonitions
    sphinx_codex_name: "Voorbeeld"
    sphinx_codex_merge_with_proof:     true # default value
    tud_change_titlesize: false
    metadata_figure_settings:
      source:
        warn_missing: true
  extra_extensions:                                  # Gives you a starter package of extensions to use in your book
    - teachbooks_favourites
    - sphinx_tudelft_theme
    - sphinx_apa_references
    - sphinx_metadata_figure

teachbooks:
  attribution_color: attributiongrey
  attribution_location: margin

bibtex_bibfiles: 
  - references.bib                                # Required for references

parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - html_image
    - linkify
    - substitution
    - tasklist
